# Generated by Django 4.2.1 on 2023-06-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Датчик')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensors')),
            ],
        ),
    ]
